"""questions table

Revision ID: 036360c29d38
Revises: f4f26a178286
Create Date: 2020-04-30 17:01:51.772862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036360c29d38'
down_revision = 'f4f26a178286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=9999), nullable=True),
    sa.Column('inputSpec', sa.String(length=9999), nullable=True),
    sa.Column('outputSpec', sa.String(length=9999), nullable=True),
    sa.Column('sampleInput', sa.String(length=9999), nullable=True),
    sa.Column('sampleOutput', sa.String(length=9999), nullable=True),
    sa.Column('timeLimit', sa.Integer(), nullable=True),
    sa.Column('memoryLimit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
