"""added more columns for Problem table

Revision ID: 1b6e10c5a8d3
Revises: 7ebf8cf4295b
Create Date: 2020-05-15 11:07:55.978872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6e10c5a8d3'
down_revision = '7ebf8cf4295b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('difficulty', sa.String(length=32), nullable=True))
    op.add_column('problem', sa.Column('numAttempts', sa.Integer(), nullable=True, default=0))
    op.add_column('problem', sa.Column('numSuccesses', sa.Integer(), nullable=True, default=0))
    op.create_index(op.f('ix_problem_difficulty'), 'problem', ['difficulty'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_difficulty'), table_name='problem')
    op.drop_column('problem', 'numSuccesses')
    op.drop_column('problem', 'numAttempts')
    op.drop_column('problem', 'difficulty')
    # ### end Alembic commands ###
