"""added correct to problems completed

Revision ID: 1df7bc107f87
Revises: ec49791cea5b
Create Date: 2020-05-24 19:28:06.983654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df7bc107f87'
down_revision = 'ec49791cea5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("problem") as batch_op:
        batch_op.create_unique_constraint('problem', ['urlTitle'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='unique')
    # ### end Alembic commands ###
