"""minor change to completed

Revision ID: 2766ba754e10
Revises: c51c7593ebec
Create Date: 2020-05-24 23:21:41.369277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2766ba754e10'
down_revision = 'c51c7593ebec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems_completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems_completed',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('questionID', sa.INTEGER(), nullable=True),
    sa.Column('user', sa.INTEGER(), nullable=True),
    sa.Column('correct', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
