"""made urltitle unique

Revision ID: 4513aede34b2
Revises: 685eaad794f7
Create Date: 2020-05-24 15:22:58.090058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4513aede34b2'
down_revision = '685eaad794f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems_completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionID', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('problems_answered')
    op.create_unique_constraint(None, 'problem', ['urlTitle'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='unique')
    op.create_table('problems_answered',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('questionID', sa.INTEGER(), nullable=True),
    sa.Column('user', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('problems_completed')
    # ### end Alembic commands ###
