"""made time a float and added problemscompleted

Revision ID: 685eaad794f7
Revises: ce36c6cbccb4
Create Date: 2020-05-24 14:55:03.687390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685eaad794f7'
down_revision = 'ce36c6cbccb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems_answered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionID', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems_answered')
    # ### end Alembic commands ###
