"""backr ref changes

Revision ID: 77dd3be075b9
Revises: c133985501a6
Create Date: 2020-05-25 11:46:24.990516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dd3be075b9'
down_revision = 'c133985501a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
