"""problems table

Revision ID: 7ebf8cf4295b
Revises: 8b207c63169a
Create Date: 2020-05-15 10:32:08.144707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebf8cf4295b'
down_revision = '8b207c63169a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('urlTitle', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timeLimit', sa.Integer(), nullable=True),
    sa.Column('memoryLimit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_title'), 'problem', ['title'], unique=True)
    op.create_table('problem_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionID', sa.Integer(), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_question_title', table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=9999), nullable=True),
    sa.Column('inputSpec', sa.VARCHAR(length=9999), nullable=True),
    sa.Column('outputSpec', sa.VARCHAR(length=9999), nullable=True),
    sa.Column('sampleInput', sa.VARCHAR(length=9999), nullable=True),
    sa.Column('sampleOutput', sa.VARCHAR(length=9999), nullable=True),
    sa.Column('timeLimit', sa.INTEGER(), nullable=True),
    sa.Column('memoryLimit', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_title', 'question', ['title'], unique=1)
    op.drop_table('problem_test_cases')
    op.drop_index(op.f('ix_problem_title'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
