"""temp

Revision ID: 804a1c2428f8
Revises: 5ffd46c4d2e7
Create Date: 2020-05-25 12:00:03.571001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804a1c2428f8'
down_revision = '5ffd46c4d2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp')
    # ### end Alembic commands ###
