"""users and questions table

Revision ID: 8b207c63169a
Revises: 
Create Date: 2020-05-04 11:52:43.680033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b207c63169a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=9999), nullable=True),
    sa.Column('inputSpec', sa.String(length=9999), nullable=True),
    sa.Column('outputSpec', sa.String(length=9999), nullable=True),
    sa.Column('sampleInput', sa.String(length=9999), nullable=True),
    sa.Column('sampleOutput', sa.String(length=9999), nullable=True),
    sa.Column('timeLimit', sa.Integer(), nullable=True),
    sa.Column('memoryLimit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_title'), 'question', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_admin'), 'user', ['admin'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_admin'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_question_title'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
