"""added points for user

Revision ID: aeed569d1c02
Revises: 1b6e10c5a8d3
Create Date: 2020-05-23 11:15:03.954422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeed569d1c02'
down_revision = '1b6e10c5a8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_problem_difficulty'), 'problem', ['difficulty'], unique=False)
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'points')
    op.drop_index(op.f('ix_problem_difficulty'), table_name='problem')
    # ### end Alembic commands ###
