"""added pref language for user

Revision ID: b5186f1cee5e
Revises: e8feea372ab5
Create Date: 2020-05-24 22:00:23.729884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5186f1cee5e'
down_revision = 'e8feea372ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('prefLanguage', sa.String(length=10)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'prefLanguage')
    # ### end Alembic commands ###
