"""minor changes

Revision ID: c133985501a6
Revises: 57ef47d9904c
Create Date: 2020-05-25 11:44:33.613320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c133985501a6'
down_revision = '57ef47d9904c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('urlTitle', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('numAttempts', sa.Integer(), nullable=True),
    sa.Column('numSuccesses', sa.Integer(), nullable=True),
    sa.Column('dateAdded', sa.String(length=10), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timeLimit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urlTitle')
    )
    op.create_index(op.f('ix_problem_title'), 'problem', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('prefLanguage', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_admin'), 'user', ['admin'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('problem_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionID', sa.Integer(), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problems_completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionID', sa.Integer(), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems_completed')
    op.drop_table('problem_test_cases')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_admin'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_problem_title'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
