"""minor change to completed

Revision ID: c51c7593ebec
Revises: e6988b4950db
Create Date: 2020-05-24 23:18:35.077723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51c7593ebec'
down_revision = 'e6988b4950db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems_completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionID', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionID'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems_completed')
    # ### end Alembic commands ###
