"""added pref language for user

Revision ID: e6988b4950db
Revises: b5186f1cee5e
Create Date: 2020-05-24 23:01:03.362730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6988b4950db'
down_revision = 'b5186f1cee5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_problems_completed_correct', table_name='problems_completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_problems_completed_correct', 'problems_completed', ['correct'], unique=False)
    # ### end Alembic commands ###
