"""added correct to problems completed

Revision ID: ec49791cea5b
Revises: 4513aede34b2
Create Date: 2020-05-24 19:19:54.946384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec49791cea5b'
down_revision = '4513aede34b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'problem', ['urlTitle'])
    op.add_column('problems_completed', sa.Column('correct', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems_completed', 'correct')
    op.drop_constraint(None, 'problem', type_='unique')
    # ### end Alembic commands ###
