#!/bin/sh

# This script will compile or run another finishing operation on a document.
#
# Compiles Java, C, C++, Python and Javascript
# Requires there respective compilers (jdk, gcc, python3
# and nodejs)
# Runs scripts based on extention or shebang

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
    *\.java) javac "$file" ;;
	*\.c) cc "$file" -o "$base" ;;
    *\.cpp) g++ -std=c++11 -O2 -Wall "$file" -o "$base" ;;
	*\.py) python3 "$file" ;;
	*\.js) node "$file";;
	*) sed 1q "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ;;
esac
